// E10 — the store page's handlers are the compiler's.
//
// `pw emit-handlers` compiles each resumable handler's BODY to
// `dist/handlers/<identity>.mjs`, and the renderer serializes onto each element
// exactly the capture paths that body reads (`resume::capture_paths`, one
// derivation for both). Until 2026-09-25 the development server wrote the
// modules itself, and the browser sent the pressed instance's address for the
// server to resolve back into an item.

import { test, expect } from "@playwright/test";

async function ready(page) {
  await page.goto("/StorePage.html");
  await page.waitForFunction(() => document.documentElement.dataset.pwReady);
}

/** The handler identities the document declares, by name. */
async function identities(page) {
  return page.evaluate(() =>
    Object.fromEntries(
      (window.__pw.parts.parts ?? [])
        .filter((p) => p.kind === "event")
        .map((p) => [p.name, p.value]),
    ),
  );
}

test("the module the browser loads is the compiled handler body", async ({ page }) => {
  await ready(page);
  const ids = await identities(page);

  // Since ADR-0058 a body is lowered as a query's is: it reads the captured
  // path, and awaits the command. What it sends is the next test's.
  const add = await (await page.request.get(`/handler/${ids.add_to_cart}.mjs`)).text();
  expect(add).toContain("// Generated by pw: resumable handler");
  // The item it captured, read by its declared fields (ADR-0172).
  expect(add).toContain('(context.captures["item"])');
  expect(add).toContain('await context.command("store.page.add_to_cart", [');

  const clear = await (await page.request.get(`/handler/${ids.clear_cart}.mjs`)).text();
  expect(clear).toContain('await context.command("store.page.clear_cart", [])');
});

test("each Add button carries exactly what its handler reads", async ({ page }) => {
  await ready(page);
  const captures = await page
    .locator("#menu button")
    .evaluateAll((els) => els.map((e) => e.dataset.pwCaptures ?? null));
  expect(captures.length).toBeGreaterThan(1);

  // What the body reads: the item, which `add_to_cart` makes its line from
  // (ADR-0172), by the fields its type declares. What the page computed for
  // the row, the price as text, is not the item's, and is not there.
  const parsed = captures.map((c) => JSON.parse(c));
  for (const c of parsed) {
    expect(Object.keys(c)).toEqual(["item"]);
    expect(Object.keys(c.item).sort()).toEqual(["description", "id", "name", "price"]);
    expect(Object.keys(c.item.price)).toEqual(["minor_units"]);
  }
  expect(new Set(parsed.map((c) => c.item.id)).size, "one item per button").toBe(parsed.length);
});

test("a press sends that button's item, computed in the browser", async ({ page }) => {
  await ready(page);
  const sent = [];
  page.on("request", (r) => {
    if (r.url().includes("/command/")) {
      sent.push({ path: new URL(r.url()).pathname, body: r.postData() });
    }
  });

  // The SECOND button, so a handler that always sent the first item fails.
  const button = page.locator("#menu button").nth(1);
  const item = JSON.parse(await button.getAttribute("data-pw-captures")).item;
  // The count moves before the request is sent (ADR-0122), so it does not
  // say the request was made; the command's answer does.
  const answered = page.waitForResponse((r) => r.url().includes("/command/"));
  await button.click();
  await expect(page.locator("#cart-count")).toHaveText("1");
  await answered;

  // The item as the page showed it, and how many (ADR-0172).
  expect(sent.map((s) => ({ path: s.path, args: JSON.parse(s.body) }))).toEqual([
    { path: "/command/store.page.add_to_cart", args: [item, 1] },
  ]);
});

test("arguments the command does not declare are refused before it runs", async ({ page }) => {
  // The module runs in the user's browser, so the server cannot know its
  // arguments came from it. They are typed by the command component's own
  // parameters: `add_to_cart(item: MenuItem, quantity: PositiveInt)` is
  // `(record, s64)` on the wire (ADR-0172).
  await ready(page);
  const item = JSON.parse(
    await page.locator("#menu button").first().getAttribute("data-pw-captures"),
  ).item;
  const nameless = { ...item };
  delete nameless.name;
  for (const data of [[item], [1, 1], ["espresso", 1], [nameless, 1], [item, 1.5], [item, "1"], {}]) {
    const response = await page.request.post("/command/store.page.add_to_cart", { data });
    expect(response.status(), JSON.stringify(data)).toBe(400);
    expect(await response.json()).toMatchObject({ committed: false });
  }
  await page.waitForTimeout(300);
  await expect(page.locator("#cart-count"), "none of them moved the cart").toHaveText("0");

  // The control: the same route with well-typed arguments does commit. With
  // an interaction, which an idempotent command requires (ADR-0121); the
  // refusals above are refused for their arguments, which are typed first.
  const ok = await page.request.post("/command/store.page.add_to_cart", {
    data: [item, 1],
    headers: { "pw-interaction": "control-1" },
  });
  expect(await ok.json()).toMatchObject({ committed: true });
  await expect(page.locator("#cart-count")).toHaveText("1");
});

test("the address-resolving command route is gone", async ({ page }) => {
  await ready(page);
  const response = await page.request.post("/command/add_to_cart?item=espresso&quantity=1");
  expect(response.status()).toBe(404);
});
