// E10 — the store page's handlers are the compiler's.
//
// `pw emit-handlers` compiles each resumable handler's BODY to
// `dist/handlers/<identity>.mjs`, and the renderer serializes onto each element
// exactly the capture paths that body reads (`resume::capture_paths`, one
// derivation for both). Until 2026-09-25 the development server wrote the
// modules itself, and the browser sent the pressed instance's address for the
// server to resolve back into an item.

import { test, expect } from "@playwright/test";

async function ready(page) {
  await page.goto("/StorePage.html");
  await page.waitForFunction(() => document.documentElement.dataset.pwReady);
}

/** The handler identities the document declares, by name. */
async function identities(page) {
  return page.evaluate(() =>
    Object.fromEntries(
      (window.__pw.parts.parts ?? [])
        .filter((p) => p.kind === "event")
        .map((p) => [p.name, p.value]),
    ),
  );
}

test("the module the browser loads is the compiled handler body", async ({ page }) => {
  await ready(page);
  const ids = await identities(page);

  const add = await (await page.request.get(`/handler/${ids.add_to_cart}.mjs`)).text();
  expect(add).toContain("// Generated by pw");
  expect(add).toContain(
    'context.command("store.page.add_to_cart", [context.captures["item"]["id"], 1])',
  );

  const clear = await (await page.request.get(`/handler/${ids.clear_cart}.mjs`)).text();
  expect(clear).toContain('context.command("store.page.clear_cart", [])');
});

test("each Add button carries exactly what its handler reads", async ({ page }) => {
  await ready(page);
  const captures = await page
    .locator("#menu button")
    .evaluateAll((els) => els.map((e) => e.dataset.pwCaptures ?? null));
  expect(captures.length).toBeGreaterThan(1);

  // The path the body reads, `item.id`, and not the whole item: a field the
  // handler does not read is not in the document to go stale there.
  const parsed = captures.map((c) => JSON.parse(c));
  for (const c of parsed) {
    expect(Object.keys(c)).toEqual(["item"]);
    expect(Object.keys(c.item)).toEqual(["id"]);
  }
  expect(new Set(parsed.map((c) => c.item.id)).size, "one item per button").toBe(parsed.length);
});

test("a press sends that button's item, computed in the browser", async ({ page }) => {
  await ready(page);
  const sent = [];
  page.on("request", (r) => {
    if (r.url().includes("/command/")) {
      sent.push({ path: new URL(r.url()).pathname, body: r.postData() });
    }
  });

  // The SECOND button, so a handler that always sent the first item fails.
  const button = page.locator("#menu button").nth(1);
  const item = JSON.parse(await button.getAttribute("data-pw-captures")).item.id;
  await button.click();
  await expect(page.locator("#cart-count")).toHaveText("1");

  expect(sent).toEqual([
    { path: "/command/store.page.add_to_cart", body: JSON.stringify([item, 1]) },
  ]);
});

test("arguments the command does not declare are refused before it runs", async ({ page }) => {
  // The module runs in the user's browser, so the server cannot know its
  // arguments came from it. They are typed by the command component's own
  // parameters: `add_to_cart(item: MenuItemId, quantity: PositiveInt)` is
  // `(string, s64)` on the wire.
  await ready(page);
  for (const data of [["espresso"], [1, 1], ["espresso", 1.5], ["espresso", "1"], {}]) {
    const response = await page.request.post("/command/store.page.add_to_cart", { data });
    expect(response.status(), JSON.stringify(data)).toBe(400);
    expect(await response.json()).toMatchObject({ committed: false });
  }
  await page.waitForTimeout(300);
  await expect(page.locator("#cart-count"), "none of them moved the cart").toHaveText("0");

  // The control: the same route with well-typed arguments does commit.
  const ok = await page.request.post("/command/store.page.add_to_cart", {
    data: ["espresso", 1],
  });
  expect(await ok.json()).toEqual({ committed: true });
  await expect(page.locator("#cart-count")).toHaveText("1");
});

test("the address-resolving command route is gone", async ({ page }) => {
  await ready(page);
  const response = await page.request.post("/command/add_to_cart?item=espresso&quantity=1");
  expect(response.status()).toBe(404);
});
