//! **What a page computes from its signals, as the browser computes it**
//! (ADR-0227).
//!
//! A value a template computes from a signal (ruling 0073-a) is the
//! browser's: it changes as a person types, and no host hears of it. The
//! compiler lifts it into a function (ADR-0226), a component a host runs for
//! the page's first render, and compiles the same function here, with the
//! browser's pure backend (`js_pure`, ADR-0044), into one module per page.
//! The runtime loads it when one of those signals first changes, and runs
//! each function with the signal's value as the document holds it, in
//! `js_pure`'s wire form.

use crate::hir::Hir;
use crate::page_values::{Derived, Live};
use crate::resolve::Workspace;
use crate::signatures::Signatures;

use super::ir::Lowering;
use super::lower::{self, Context};

/// One page's module, or why it did not compile.
#[derive(Debug, Clone)]
pub struct Compiled {
    /// The page's template path: `feed.app.Home`.
    pub page: String,
    /// Its source: each function, and `parts`, each part's by its number.
    pub module: Result<String, String>,
}

/// **Every page's module.** A page that computes nothing from a signal has
/// none, and is not listed.
pub fn compile(units: &[crate::check::Unit]) -> Result<Vec<Compiled>, String> {
    let hirs: Vec<&Hir> = units.iter().map(|u| &u.hir).collect();
    let ws = Workspace::build(&hirs);
    let sigs = Signatures::build(&ws, &hirs);
    let contracts = crate::contract::contracts(&hirs, &sigs, &ws);
    let cx = Context {
        hirs: &hirs,
        ws: &ws,
        sigs: &sigs,
        contracts: &contracts,
    };
    lower::Checked::of(units, cx).map_err(|ds| {
        format!(
            "the program does not check, so nothing is compiled: {}",
            ds.iter()
                .map(|d| format!("[{}] {}", d.code, d.message))
                .collect::<Vec<_>>()
                .join("; ")
        )
    })?;
    let cx = Context {
        hirs: &hirs,
        ws: &ws,
        sigs: &sigs,
        contracts: &contracts,
    };
    let derived = crate::page_values::derived(&hirs, &ws, &sigs);
    let mut out = Vec::new();
    for planned in crate::page_values::pages(&hirs, &ws, &sigs) {
        let Ok(plan) = &planned.plan else { continue };
        let computed: Vec<&Live> = plan.live.iter().filter(|l| !l.derived.is_empty()).collect();
        if computed.is_empty() {
            continue;
        }
        out.push(Compiled {
            module: module(&cx, &planned.page, &computed, &derived),
            page: planned.page,
        });
    }
    Ok(out)
}

/// **One page's module**: each function the compiler lifted, as `js_pure`
/// writes one, and each part's, taking the signal's value in its wire form.
fn module(
    cx: &Context<'_>,
    page: &str,
    computed: &[&Live],
    derived: &[Derived],
) -> Result<String, String> {
    let mut functions = Vec::new();
    for live in computed {
        let d = derived
            .iter()
            .find(|d| d.component_id == live.derived)
            .ok_or_else(|| format!("part {} of `{page}` lifted no function", live.part))?;
        match lower::hole(cx, d) {
            Lowering::Lowered(f) => functions.push(f),
            other => return Err(format!("part {} of `{page}`: {other}", live.part)),
        }
    }
    let program = lower::program_of(cx, functions);
    let mut source = format!(
        "// Generated by pw: what `{page}` computes from its signals (ADR-0227). Do not edit.\n\n"
    );
    for (n, f) in program.functions.iter().enumerate() {
        let js = super::js_pure::isolated(f, &program)?;
        source.push_str(&format!("const f{n} = {js};\n\n"));
    }
    source.push_str("export const parts = {\n");
    for (n, live) in computed.iter().enumerate() {
        let f = &program.functions[n];
        let (_, input) = f
            .params
            .first()
            .ok_or_else(|| format!("part {} of `{page}` takes nothing", live.part))?;
        let decode = super::js_pure::decoder(&program, input, "j")?;
        source.push_str(&format!("  \"{}\": (j) => f{n}({decode}),\n", live.part));
    }
    source.push_str("};\n");
    Ok(source)
}
