//! The compiler's contract, read by the host, field for field.
//!
//! ADR-0018 and ADR-0020: this crate does not link the compiler, so the types
//! are mirrored by field name. What makes that a boundary rather than a hope is
//! that this test reads output the REAL compiler produced — the artifact
//! committed at `docs/evidence/E8/component-contracts.json`, regenerated by
//! `just e8-contracts`.
//!
//! A rename on either side fails here, loudly, rather than becoming an empty
//! capability set at instantiation time. An empty capability set is the worst
//! possible failure mode for this artifact: it means every audit passes.

use std::collections::{BTreeMap, BTreeSet};

use pw_host::*;

fn committed() -> Vec<ComponentContract> {
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../docs/evidence/E8/component-contracts.json");
    let text = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("{}: {e} — run `just e8-contracts`", path.display()));
    ComponentContract::from_json(&text).expect("the compiler's contracts parse here")
}

fn find(id: &str) -> ComponentContract {
    committed()
        .into_iter()
        .find(|c| c.component_id == id)
        .unwrap_or_else(|| panic!("no contract for {id}"))
}

#[test]
fn the_compilers_contracts_deserialize_with_every_field_populated() {
    let all = committed();
    assert!(all.len() >= 8, "the store program has several components");

    for c in &all {
        assert!(!c.component_id.is_empty());
        assert!(!c.abi_schema.is_empty());
        assert!(!c.exports.is_empty(), "{} exports nothing", c.component_id);
        // Every import names the capability that authorises it, and that
        // capability is one the contract actually requires. A mirror that
        // dropped `capability` would leave this empty and the audit would still
        // "work" — while every refusal became unexplainable.
        for i in &c.imports {
            assert!(
                !i.capability.is_empty(),
                "{} has a nameless import",
                c.component_id
            );
            assert!(
                c.required_capabilities
                    .iter()
                    .any(|r| r.name() == i.capability),
                "{}: import {} claims `{}`, which it does not require",
                c.component_id,
                i.key(),
                i.capability
            );
        }
    }
}

#[test]
fn a_capability_survives_the_crossing_with_its_argument() {
    // The one field most likely to be silently dropped, because it is optional
    // and most capabilities do not have one. E2D recorded what losing it costs.
    let all = committed();
    let with_argument: Vec<String> = all
        .iter()
        .flat_map(|c| &c.required_capabilities)
        .filter(|c| c.argument.is_some())
        .map(Capability::name)
        .collect();
    assert!(
        !with_argument.is_empty()
            || all
                .iter()
                .all(|c| c.required_capabilities.iter().all(|r| r.argument.is_none())),
        "if the corpus has typed capabilities they must survive: {with_argument:?}"
    );

    // Whatever the corpus happens to contain, the ROUND TRIP must keep it.
    let typed = Capability {
        family: "database".into(),
        operation: "read".into(),
        argument: Some("Stores".into()),
    };
    let text = serde_json::to_string(&typed).expect("serialize");
    let back: Capability = serde_json::from_str(&text).expect("deserialize");
    assert_eq!(back, typed);
    assert_eq!(back.name(), "database.read<Stores>");
}

#[test]
fn the_store_page_renders_without_authority_and_its_command_does_not() {
    // ADR-0020's least-authority decision, checked against the real artifact
    // rather than against a fixture written to agree with it.
    let page = find("store.page.StorePage");
    assert!(
        page.required_capabilities.is_empty(),
        "rendering the store page needs no capability, got {:?}",
        page.required_capabilities
    );

    let command = find("store.page.add_to_cart");
    assert!(
        !command.required_capabilities.is_empty(),
        "and the command that writes does"
    );
    assert_eq!(command.allowed_placements, ["origin"]);
}

#[test]
fn the_real_contracts_drive_a_real_admission() {
    // The end of the chain, on committed compiler output: the page runs in a
    // browser, and the command it triggers does not.
    let topology = Topology {
        nodes: vec![
            Node {
                name: "laptop".into(),
                world: "browser".into(),
                grants: BTreeSet::new(),
            },
            Node {
                name: "origin-1".into(),
                world: "origin".into(),
                grants: BTreeSet::from(["database.read".to_string(), "database.write".to_string()]),
            },
        ],
    };

    let page = find("store.page.StorePage");
    assert!(
        admit(&page, &topology, "laptop", &[]).is_admitted(),
        "a page with no capability requirement renders on a browser node"
    );

    let command = find("store.page.add_to_cart");
    let actual: Vec<String> = command.imports.iter().map(|i| i.key()).collect();
    assert!(admit(&command, &topology, "origin-1", &actual).is_admitted());
    assert!(
        !admit(&command, &topology, "laptop", &actual).is_admitted(),
        "and it does not run on the laptop, whatever the page does"
    );

    // The instance receives handles for exactly what it requires.
    let backing = BTreeMap::from([("database.write".to_string(), "connection".to_string())]);
    let granted = Granted::from(&admit(&command, &topology, "origin-1", &actual), &backing)
        .expect("admitted");
    assert_eq!(granted.count(), command.required_capabilities.len());
}
