//! **E10: resumable handlers compile to JavaScript modules** (`backend::js`).
//!
//! Charter §14 M10 task 2 puts "generated modern JavaScript modules for
//! handlers" first. The store's two handlers compile to the one call each body
//! makes. What a module reads of its captures is exactly what the template IR
//! tells the renderer to serialize, and a module and its event part name one
//! handler. Everything outside the supported set is refused by name, never
//! compiled to something plausible.

use std::collections::BTreeMap;

use pw_core::backend::js::{self, HandlerModule};
use pw_core::backend::wasm::Encoding;
use pw_core::check::Unit;
use pw_core::hir::Hir;
use pw_core::lower::lower_file;
use pw_core::resolve::Workspace;
use pw_core::signatures::Signatures;
use pw_syntax::parse_tree;

fn store_units() -> Vec<Unit> {
    let root = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../..");
    let mut paths = Vec::new();
    for d in [
        "packages/pw-std",
        "packages/pw-platform-web",
        "examples/lib",
        "examples/store",
    ] {
        let mut ps: Vec<std::path::PathBuf> = std::fs::read_dir(root.join(d))
            .unwrap_or_else(|e| panic!("{d}: {e}"))
            .map(|e| e.expect("entry").path())
            .filter(|p| p.extension().is_some_and(|x| x == "pw"))
            .collect();
        ps.sort();
        paths.extend(ps);
    }
    paths.push(root.join("examples/domain.pw"));
    paths
        .into_iter()
        .map(|p| {
            let src = std::fs::read_to_string(&p).expect("read");
            Unit {
                path: p.display().to_string(),
                hir: lower_file(&src, &parse_tree(&src).green),
                src,
            }
        })
        .collect()
}

/// Every compiled module, by the behaviour's name; a refusal fails the test.
fn modules(units: &[Unit]) -> BTreeMap<String, HandlerModule> {
    js::compile(units)
        .expect("the program checks")
        .into_iter()
        .map(|c| match c.module {
            Encoding::Encoded(m) => (m.name.clone(), m),
            other => panic!("a handler in `{}` was not compiled: {other}", c.declaration),
        })
        .collect()
}

/// `(name, handler identity, capture paths)` for every event part in the
/// template IR, built with the identities the resume artifacts derived, as
/// `pw emit-template` builds it, and read back from its JSON, as the runtime
/// and the renderer read it.
fn event_parts(units: &[Unit]) -> Vec<(String, String, Vec<String>)> {
    let hirs: Vec<&Hir> = units.iter().map(|u| &u.hir).collect();
    let ws = Workspace::build(&hirs);
    let sigs = Signatures::build(&ws, &hirs);
    let mut handlers = pw_core::template_ir::Handlers::new();
    for u in units {
        for (decl, lambda, m, _) in pw_core::resume_artifacts::located(
            &u.src,
            &u.hir,
            &sigs,
            pw_core::resume_artifacts::BUILD,
        ) {
            handlers.insert((decl, lambda), m.handler);
        }
    }
    let ir = serde_json::to_value(pw_core::template_ir::build_with(&hirs, &handlers))
        .expect("the IR serializes");
    let mut out = Vec::new();
    let mut stack = vec![&ir];
    while let Some(v) = stack.pop() {
        match v {
            serde_json::Value::Object(o) => {
                if o.contains_key("event") && o.contains_key("handler") {
                    let text = |k: &str| o[k].as_str().unwrap_or_default().to_string();
                    let captures = o
                        .get("captures")
                        .and_then(|c| c.as_array())
                        .map(|c| c.iter().map(|p| p.as_str().unwrap().to_string()).collect())
                        .unwrap_or_default();
                    out.push((text("name"), text("handler"), captures));
                }
                stack.extend(o.values());
            }
            serde_json::Value::Array(a) => stack.extend(a),
            _ => {}
        }
    }
    out.sort();
    out
}

// --- the store ------------------------------------------------------------

#[test]
fn the_stores_handlers_compile_to_the_call_their_bodies_make() {
    let modules = modules(&store_units());
    assert_eq!(
        modules.keys().collect::<Vec<_>>(),
        ["add_to_cart", "clear_cart"]
    );

    // on:press={resumable(captures = { item }) => add_to_cart(item.id, PositiveInt(1))}
    let add = &modules["add_to_cart"];
    println!("{}", add.source);
    assert_eq!(add.command, "store.page.add_to_cart");
    assert_eq!(
        add.source,
        format!(
            "// Generated by pw: resumable handler {id}. Do not edit.\n\
             export const name = \"add_to_cart\";\n\
             export const handler = \"{id}\";\n\
             export async function run(context) {{\n\
             \x20 return await context.command(\"store.page.add_to_cart\", \
             [context.captures[\"item\"][\"id\"], 1]);\n\
             }}\n",
            id = add.identity
        ),
        "the captured item's id, and PositiveInt(1) as its representation"
    );

    // on:press={resumable() => clear_cart()}
    let clear = &modules["clear_cart"];
    println!("{}", clear.source);
    assert_eq!(clear.command, "store.page.clear_cart");
    assert!(
        clear
            .source
            .contains("return await context.command(\"store.page.clear_cart\", []);"),
        "{}",
        clear.source
    );
}

/// **A module and its event part are one handler.** The identity the runtime
/// fetches by, the name its manifest is looked up by, and the capture paths
/// the renderer serializes all agree with what the module was compiled as and
/// what it reads.
#[test]
fn a_module_and_its_event_part_name_one_handler() {
    let units = store_units();
    let modules = modules(&units);
    let parts = event_parts(&units);
    assert_eq!(parts.len(), 2, "{parts:?}");
    for (name, identity, captures) in &parts {
        let m = &modules[name];
        assert_eq!(&m.identity, identity, "{name}: one identity");
        for path in captures {
            let read: String = path.split('.').map(|s| format!("[\"{s}\"]")).collect();
            assert!(
                m.source.contains(&format!("context.captures{read}")),
                "{name} reads `{path}`, which the document carries"
            );
        }
    }
    let captures: BTreeMap<&str, &Vec<String>> =
        parts.iter().map(|(n, _, c)| (n.as_str(), c)).collect();
    assert_eq!(
        captures["add_to_cart"],
        &["item.id"],
        "the path read, not the whole item"
    );
    assert!(
        captures["clear_cart"].is_empty(),
        "reads nothing it captured"
    );
}

/// **Every command a handler calls is a component the contracts name.** The
/// handler calls by `contract::component_id`, and so do the contracts; a
/// second derivation that disagreed would send a press to a component no host
/// has a contract for.
#[test]
fn a_handler_calls_its_command_by_the_contracts_own_id() {
    let units = store_units();
    let hirs: Vec<&Hir> = units.iter().map(|u| &u.hir).collect();
    let ws = Workspace::build(&hirs);
    let sigs = Signatures::build(&ws, &hirs);
    let ids: Vec<String> = pw_core::contract::contracts(&hirs, &sigs, &ws)
        .into_iter()
        .map(|c| c.component_id)
        .collect();
    for m in modules(&units).values() {
        assert!(ids.contains(&m.command), "`{}` has no contract", m.command);
    }
}

#[test]
fn a_program_that_does_not_check_compiles_no_handlers() {
    // The store without the standard packages it imports: it does not check,
    // so nothing is compiled, although every handler in it would be.
    let units: Vec<Unit> = store_units()
        .into_iter()
        .filter(|u| !u.path.contains("packages/"))
        .collect();
    let err = js::compile(&units).expect_err("does not check");
    assert!(err.contains("does not check"), "{err}");
}

// --- the supported set, and the refusals ------------------------------------

const SHOP: &str = "\
module shop.ui

opaque type Qty = Int
opaque type Sku = String
type Item = Item { id: Sku, name: String }
type Pack = Pack { n: Int }

command Buy(id: Sku, qty: Qty) -> Int { 0 }
command Rename(id: Sku, name: String) -> Int { 0 }
command Ship(p: Pack) -> Int { 0 }
query Look(id: Sku) -> Int { 0 }
fn helper(x: Int) -> Int { x }

page Shop(items: List<Item>, sku: Sku) {
    view {
        <ul>
            {#each items as item (item.id)}
                <li>
                    <button on:press={resumable(captures = { item }) => HANDLER}>Go</button>
                </li>
            {/each}
        </ul>
    }
}
";

/// The one handler in `SHOP` with `HANDLER` replaced, compiled without the
/// check gate: these programs are about the backend's refusals, and a refusal
/// must hold whatever produced the program.
fn shop(handler: &str) -> Encoding<HandlerModule> {
    let src = SHOP.replace("HANDLER", handler);
    let hir = lower_file(&src, &parse_tree(&src).green);
    let hirs = vec![&hir];
    let ws = Workspace::build(&hirs);
    let sigs = Signatures::build(&ws, &hirs);
    let mut all = js::handlers(&hirs, &[src.as_str()], &ws, &sigs);
    assert_eq!(all.len(), 1, "one handler in `{handler}`");
    all.remove(0).module
}

fn compiled(handler: &str) -> HandlerModule {
    match shop(handler) {
        Encoding::Encoded(m) => m,
        other => panic!("`{handler}` did not compile: {other}"),
    }
}

fn refused(handler: &str, construct: &str, reason: &str) {
    match shop(handler) {
        Encoding::Unsupported {
            construct: c,
            reason: r,
        } => {
            println!("refused `{handler}`: {c}: {r}");
            assert_eq!(c, construct, "`{handler}`: {r}");
            assert!(r.contains(reason), "`{handler}`: {r}");
        }
        other => panic!("`{handler}` must be refused as {construct}, got {other:?}"),
    }
}

#[test]
fn an_opaque_constructor_sends_its_representation() {
    let m = compiled("Buy(item.id, Qty(2))");
    assert!(
        m.source
            .contains("context.command(\"shop.ui.Buy\", [context.captures[\"item\"][\"id\"], 2])"),
        "{}",
        m.source
    );
}

#[test]
fn each_path_read_is_read_where_the_document_carries_it() {
    let m = compiled("Rename(item.id, item.name)");
    assert!(
        m.source
            .contains("[context.captures[\"item\"][\"id\"], context.captures[\"item\"][\"name\"]]"),
        "{}",
        m.source
    );
    // A string literal sends its VALUE. Its token keeps the quotes, and a
    // module that sent the token would send `"new name"` with the quotes in it.
    let m = compiled("Rename(item.id, \"new name\")");
    assert!(
        m.source
            .contains(r#"[context.captures["item"]["id"], "new name"]"#),
        "{}",
        m.source
    );
}

#[test]
fn a_string_whose_value_needs_an_escape_rule_is_refused() {
    // The language does not say what `\"` means inside a string. The Koka and
    // Marko backends pass the token to their targets' rules; this one refuses
    // rather than choose JavaScript's.
    refused(
        "Rename(item.id, \"new \\\"name\\\"\")",
        "a string literal whose escapes the language does not define",
        "escape rule",
    );
}

#[test]
fn a_handler_that_calls_no_command_is_refused() {
    refused(
        "Look(item.id)",
        "a handler that does not call a command",
        "is a Query",
    );
    refused(
        "helper(1)",
        "a handler that does not call a command",
        "is a Fn",
    );
}

#[test]
fn computation_in_the_browser_is_refused_by_name() {
    refused(
        "Buy(item.id, Qty(1 + 1))",
        "an expression outside the handler backend",
        "a binary operator",
    );
    refused(
        "Buy(item.id, Qty(helper(1)))",
        "a call inside a handler's arguments",
        "helper",
    );
}

#[test]
fn a_value_the_handler_did_not_capture_is_refused() {
    // `sku` is the page's parameter. The document does not carry it for this
    // handler, so the handler would read nothing.
    refused(
        "Buy(sku, Qty(1))",
        "a value the handler does not capture",
        "`sku`",
    );
}

#[test]
fn an_integer_a_javascript_number_cannot_hold_is_refused() {
    compiled("Buy(item.id, Qty(9007199254740992))");
    refused(
        "Buy(item.id, Qty(9007199254740993))",
        "an integer a JavaScript number cannot hold exactly",
        "±2^53",
    );
}

#[test]
fn a_command_parameter_a_browser_cannot_send_is_refused() {
    refused(
        "Ship(Pack(1))",
        "a command parameter a browser cannot send",
        "`Pack`",
    );
}
