//! Generating Marko templates from `.pw` source (ADR-0017).
//!
//! Hermetic: these assert what is generated, never that it renders. Building
//! and serving it needs Node and Marko, and lives in
//! `spikes/pw-to-marko/run.sh` with its evidence under `docs/evidence/E3/`.

use pw_core::lower::lower_file;
use pw_core::marko::render_module;
use pw_syntax::parse_tree;

fn render(src: &str) -> pw_core::marko::Rendered {
    let p = parse_tree(src);
    assert!(p.ok(), "fixture must parse: {:?}", p.errors);
    render_module(&lower_file(src, &p.green), "test.pw")
}

fn example(name: &str) -> String {
    let p = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join(format!("../../examples/{name}/app.pw"));
    std::fs::read_to_string(p).unwrap_or_else(|e| panic!("{name}/app.pw: {e}"))
}

#[test]
fn the_static_example_renders_with_nothing_skipped() {
    let out = render(&example("hello-static"));
    assert!(out.skipped.is_empty(), "{:?}", out.skipped);
    assert_eq!(out.files.len(), 1);
    let (name, text) = &out.files[0];
    assert_eq!(name, "HelloStatic.marko");

    // No state, no handlers, no interpolation — the zero-JS route depends on
    // the template containing nothing that needs a client.
    assert!(
        !text.contains("${"),
        "a static route must interpolate nothing"
    );
    assert!(!text.contains("onClick"), "and have no handlers");
    assert!(text.contains("<h1>Blue Bottle</h1>"));
}

#[test]
fn generated_files_say_they_are_generated() {
    // ADR-0017 property 3. If a generated file looks authorable, someone edits
    // it, and the `.pw` source stops being the truth.
    let out = render(&example("counter"));
    let (_, text) = &out.files[0];
    assert!(
        text.starts_with("// GENERATED by pw from `test.pw`"),
        "{text}"
    );
    assert!(text.contains("Do not edit"));
}

#[test]
fn a_semantic_event_is_translated_not_passed_through() {
    // `press` is a `pw` event and `onClick` is a DOM one. Passing an unknown
    // name straight through would let a `.pw` file address the DOM directly,
    // which is the coupling charter §11 exists to prevent.
    let out = render(&example("counter"));
    let (_, text) = &out.files[0];
    assert!(
        text.contains(r#"<button id="add" onClick() { count = count + 1 }>Add to cart</button>"#),
        "{text}"
    );
    assert!(
        !text.contains("on:press"),
        "the pw spelling must not survive"
    );

    // Negative control: an event with no mapping is refused, not guessed.
    let out = render("module m\nview V() !{} {\n    <button on:levitate={f()}>x</button>\n}\n");
    assert!(out.files.is_empty());
    assert_eq!(out.skipped.len(), 1);
    assert!(
        out.skipped[0].reason.contains("levitate"),
        "{:?}",
        out.skipped[0]
    );
}

#[test]
fn interpolation_becomes_a_marko_expression() {
    let out = render(&example("counter"));
    let (_, text) = &out.files[0];
    assert!(
        text.contains(r#"<output id="count">${count}</output>"#),
        "{text}"
    );
    // A view's own `let mut` becomes reactive state — without it the counter
    // has nothing to increment.
    assert!(text.contains("<let/count=0>"), "{text}");
}

#[test]
fn a_view_parameter_becomes_input_and_a_local_does_not() {
    // Marko passes attributes as `input`. The first version emitted
    // `<attrs/{ count }>` — written from memory, and the build rejected it.
    // Both halves are asserted here so neither can regress into the other.
    let out = render(
        "module m\nview V(title: String) !{} {\n    let mut n = 0\n    <p>{title} {n}</p>\n}\n",
    );
    let (_, text) = &out.files[0];
    assert!(text.contains("<let/n=0>"), "{text}");
    assert!(
        text.contains("${input.title}"),
        "a parameter arrives as input: {text}"
    );
    assert!(
        text.contains("${n}") && !text.contains("input.n"),
        "a local binding is not input: {text}"
    );
}

#[test]
fn whitespace_between_inline_content_survives() {
    // `In cart: <output>` lost its space in the first version, because the
    // parser treated inter-element whitespace as trivia. In HTML that space is
    // content, and the page rendered "In cart:5".
    let out = render("module m\nview V() !{} {\n    <p>In cart: <b>{n}</b></p>\n}\n");
    let (_, text) = &out.files[0];
    assert!(text.contains("<p>In cart: <b>${n}</b></p>"), "{text}");
}

#[test]
fn whitespace_on_one_line_is_content_and_a_newline_is_formatting() {
    // Marko strips whitespace between elements in a template, so block layout
    // does NOT round-trip a space the author wrote — the page rendered
    // "Espresso$3.50". Written from the browser failure, not from the template.
    let out = render(
        "module m\nview V() !{} {\n    <ul><li><span>a</span> <span>b</span></li></ul>\n}\n",
    );
    let (_, text) = &out.files[0];
    assert!(
        text.contains("<li><span>a</span> <span>b</span></li>"),
        "a space the author wrote on one line must survive verbatim:\n{text}"
    );

    // Control: children separated by a newline are formatting, and must NOT be
    // flattened onto one line — that would put a whole page on one line.
    let out = render(
        "module m\nview V() !{} {\n    <ul>\n        <li>a</li>\n        <li>b</li>\n    </ul>\n}\n",
    );
    let (_, text) = &out.files[0];
    assert!(text.contains("<ul>\n"), "block layout expected:\n{text}");
    assert!(text.contains("  <li>a</li>\n"), "{text}");
}

#[test]
fn an_unmodelled_construct_is_skipped_with_a_reason() {
    // ADR-0017 property 4. An approximation renders, which is worse than not
    // rendering: the page looks right and is wrong.
    let out = render(
        "module m\nview V() !{} {\n    {#each items as i (i.id)}<li>{i.name}</li>{/each}\n}\n",
    );
    assert!(out.files.is_empty(), "nothing may be emitted");
    assert_eq!(out.skipped.len(), 1);
    assert!(
        out.skipped[0].reason.contains("directive"),
        "{:?}",
        out.skipped
    );
}

#[test]
fn only_renderable_declarations_are_considered() {
    let out = render(
        "module m\n\
         fn helper() -> Int !{} { 1 }\n\
         view V() !{} { <p>hi</p> }\n",
    );
    assert_eq!(out.files.len(), 1, "a plain fn is not a template");
    assert!(out.skipped.is_empty(), "and is not reported as a failure");
}

#[test]
fn no_generated_marko_is_tracked_in_the_repository() {
    // ADR-0017 property 3, enforced. Build output beside authoring source is
    // exactly what charter §14 M3 task 3 forbids.
    let root = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../..");
    let out = std::process::Command::new("git")
        .arg("-C")
        .arg(&root)
        .args(["ls-files", "*.marko"])
        .output()
        .expect("git");
    let tracked: Vec<&str> = std::str::from_utf8(&out.stdout)
        .unwrap_or("")
        .lines()
        .filter(|l| !l.is_empty())
        .collect();
    for f in &tracked {
        // The E0 spike's hand-written templates predate the adapter and are
        // authoring source for that spike, not build output.
        assert!(
            f.starts_with("spikes/marko-stream-resume/"),
            "generated Marko must not be tracked: {f}"
        );
    }
}
