#!/usr/bin/env bash
# just env-record — regenerate docs/environment/macbook.md and tools/versions.lock.
# Read-only with respect to the toolchain; only writes the two record files.
# PROJECT_CHARTER.md §13.1 and §13.3.

set -uo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
export PATH="$REPO_ROOT/.toolchain/prefix/bin:$PATH"
OUT="$REPO_ROOT/docs/environment/macbook.md"
LOCK="$REPO_ROOT/tools/versions.lock"
mkdir -p "$(dirname "$OUT")" "$(dirname "$LOCK")"

v() { command -v "$1" >/dev/null 2>&1 && (eval "$2" 2>/dev/null | head -1) || echo "(absent)"; }

STAMP="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

{
    echo "# MacBook environment record"
    echo
    echo "Generated by \`just env-record\` at $STAMP (UTC)."
    echo "Regenerate rather than hand-editing. PROJECT_CHARTER.md §13.1."
    echo
    echo '## Host'
    echo
    echo '```text'
    echo "uname -a          : $(uname -a)"
    echo "uname -m          : $(uname -m)"
    echo "sw_vers           : $(sw_vers -productName 2>/dev/null) $(sw_vers -productVersion 2>/dev/null) ($(sw_vers -buildVersion 2>/dev/null))"
    echo "hw.model          : $(sysctl -n hw.model 2>/dev/null)"
    echo "cpu               : $(sysctl -n machdep.cpu.brand_string 2>/dev/null)"
    echo "hw.ncpu           : $(sysctl -n hw.ncpu 2>/dev/null)"
    echo "hw.memsize        : $(sysctl -n hw.memsize 2>/dev/null) bytes ($(( $(sysctl -n hw.memsize 2>/dev/null || echo 0) / 1073741824 )) GiB)"
    echo "xcode-select -p   : $(xcode-select -p 2>&1)"
    echo "CLT version       : $(pkgutil --pkg-info=com.apple.pkg.CLTools_Executables 2>/dev/null | awk -F': ' '/^version/{print $2}')"
    echo '```'
    echo
    echo '## Toolchain'
    echo
    echo '```text'
    printf 'brew              : %s\n' "$(v brew 'brew --version')"
    printf 'git               : %s\n' "$(v git 'git --version')"
    printf 'rustup            : %s\n' "$(v rustup 'rustup --version')"
    printf 'rustc             : %s\n' "$(v rustc 'rustc --version')"
    printf 'cargo             : %s\n' "$(v cargo 'cargo --version')"
    printf 'rust targets      : %s\n' "$(rustup target list --installed 2>/dev/null | tr '\n' ' ')"
    printf 'node              : %s\n' "$(v node 'node --version')"
    printf 'pnpm              : %s\n' "$(v pnpm 'pnpm --version')"
    printf 'corepack          : %s\n' "$(v corepack 'corepack --version')"
    printf 'koka              : %s\n' "$(v koka 'koka --version | head -1')"
    printf 'wasmtime          : %s\n' "$(v wasmtime 'wasmtime --version')"
    printf 'just              : %s\n' "$(v just 'just --version')"
    printf 'jq                : %s\n' "$(v jq 'jq --version')"
    printf 'openssl           : %s\n' "$(v openssl 'openssl version')"
    printf 'limactl           : %s\n' "$(v limactl 'limactl --version')"
    printf 'mkcert            : %s\n' "$(v mkcert 'mkcert --version')"
    printf 'hyperfine         : %s\n' "$(v hyperfine 'hyperfine --version')"
    echo '```'
    echo
    echo '## Deviations from the charter'
    echo
    echo 'The charter (§1, §14 M11) assumes an M3 Max with 64 GB RAM. See'
    echo '`docs/ASSUMPTIONS.md` A-001 for the recorded deviation and its consequences.'
} > "$OUT"

{
    echo "# tools/versions.lock — what was ACTUALLY tested on this host."
    echo "# Generated by 'just env-record'. PROJECT_CHARTER.md §13.3."
    echo "# 'just doctor' compares live versions against these strings."
    echo "# generated_at = $STAMP"
    echo
    echo "macos            = $(sw_vers -productVersion 2>/dev/null) ($(sw_vers -buildVersion 2>/dev/null))"
    echo "xcode_clt        = $(pkgutil --pkg-info=com.apple.pkg.CLTools_Executables 2>/dev/null | awk -F': ' '/^version/{print $2}')"
    echo "arch             = $(uname -m)"
    echo "git              = $(v git 'git --version')"
    echo "rustc            = $(v rustc 'rustc --version')"
    echo "cargo            = $(v cargo 'cargo --version')"
    echo "node             = $(v node 'node --version')"
    echo "pnpm             = $(v pnpm 'pnpm --version')"
    echo "koka             = $(v koka 'koka --version | head -1')"
    echo "wasmtime         = $(v wasmtime 'wasmtime --version')"
    echo "just             = $(v just 'just --version')"
    echo "jq               = $(v jq 'jq --version')"
    echo "limactl          = $(v limactl 'limactl --version')"
    echo
    echo "# Pinned but not necessarily installed yet (npm side is pinned in"
    echo "# package.json + pnpm-lock.yaml; these are the versions verified on the"
    echo "# npm registry on 2026-08-05):"
    echo "npm_marko        = 6.3.32"
    echo "npm_marko_run    = 0.11.8"
    echo "npm_marko_vite   = 6.1.9"
    echo "npm_vite         = 8.2.0"
    echo "npm_playwright   = 1.62.1"
} > "$LOCK"

echo "wrote $OUT"
echo "wrote $LOCK"
