//! The compiler's graph, read by the runtime that consumes it.
//!
//! `store-graph.json` is real output — `pw emit-graph` over the store demo,
//! regenerated by `just materialize`. Reading it here is what makes ADR-0018's
//! boundary a boundary rather than a hope: the two crates share no type, so the
//! only thing that can prove they agree is one of them reading the other's
//! bytes.
//!
//! A test that built the graph in-process would be checking a shape this crate
//! invented. A field renamed on the compiler's side would then be invisible
//! here until an empty list at run time turned into a fragment nothing ever
//! invalidated — which is precisely the silent failure this milestone is about,
//! reproduced by the test suite meant to prevent it.
//!
//! The other half is in `pw-cli`: `the_committed_graph_matches_what_the_compiler_emits`
//! regenerates this file and compares, so a rename fails a test rather than
//! ageing a fixture.

use pw_materialize::*;

fn store_graph() -> Graph {
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/store-graph.json");
    let src = std::fs::read_to_string(&path).expect("tests/store-graph.json");
    Graph::from_json(&src).expect("the compiler's graph deserializes")
}

#[test]
fn the_compilers_graph_deserializes_with_its_edges_intact() {
    let g = store_graph();
    assert!(!g.nodes.is_empty(), "nodes survived the boundary");
    assert!(!g.edges.is_empty(), "edges survived the boundary");
    assert!(
        g.dangling.is_empty(),
        "the demo's graph has no edge to nothing"
    );
}

#[test]
fn the_menu_fragment_listens_for_the_events_the_source_declares() {
    let g = store_graph();
    let listening = g.fragments_listening_for("Events.MenuChanged");
    assert_eq!(
        listening,
        vec!["store.menu_fragment.MenuFragment".to_string()],
        "the fragment `examples/store/menu.pw` declares"
    );

    // A negative control in the same test: an event the fragment does NOT
    // declare must reach nothing, or "listens for X" is just "listens".
    assert!(
        g.fragments_listening_for("Events.CartChanged").is_empty(),
        "a cart event must not reach the menu fragment"
    );
}

#[test]
fn the_menu_fragment_depends_on_the_queries_the_source_names() {
    let g = store_graph();
    let deps = g.dependencies_of("store.menu_fragment.MenuFragment");
    assert!(
        deps.contains(&"store.page.Menu".to_string()),
        "got {deps:?}"
    );
    assert!(
        deps.contains(&"store.page.Store".to_string()),
        "got {deps:?}"
    );
    assert!(
        !deps.contains(&"store.page.Cart".to_string()),
        "the shared fragment must not depend on the session cart; got {deps:?}"
    );
}

#[test]
fn the_declared_key_dimensions_survive_the_boundary() {
    // The gap this closes: an entry key built by hand that omits a dimension
    // the declaration requires produces a cache HIT for the wrong reader, and
    // no invalidation test finds a hit.
    //
    // `code_version` is deliberately NOT here. It stopped being a dimension an
    // author declares when it became a namespace the platform injects — see
    // `the_compatibility_generation_is_not_a_dimension_a_caller_supplies`.
    let g = store_graph();
    let dims = g.dimensions_of("store.menu_fragment.MenuFragment");
    assert!(dims.contains(&Dimension::Locale), "got {dims:?}");
    assert!(dims.contains(&Dimension::Tenant), "got {dims:?}");
    assert!(dims.contains(&Dimension::PolicyVersion), "got {dims:?}");
    assert!(dims.contains(&Dimension::PrivacyPartition), "got {dims:?}");
}

#[test]
fn an_entry_key_built_from_the_graph_separates_every_declared_dimension() {
    // The two halves joined: the compiler says which dimensions separate this
    // fragment's entries, and the runtime builds a key from that answer rather
    // than from a list someone typed twice.
    let g = store_graph();
    let fragment = "store.menu_fragment.MenuFragment";
    let build = |locale: &str| {
        let mut k = EntryKey::new(fragment, &["47"]);
        for d in g.dimensions_of(fragment) {
            let v = match d {
                Dimension::Locale => locale,
                Dimension::Tenant => "acme",
                Dimension::PrivacyPartition => "public",
                Dimension::PolicyVersion => "v3",
            };
            k = k.with(d.key_name(), v);
        }
        k
    };

    let clock = Clock::new();
    let m = Materializer::new(clock.clone(), "build-1");
    m.declare(fragment, FragmentPolicy::default());
    clock.advance(1);
    m.regenerate(&build("en"), None, || Ok("English menu".to_string()));

    assert_eq!(
        m.read(&build("fr")),
        Read::Missing,
        "a French reader must not be served the English entry"
    );
    assert_eq!(
        m.read(&build("en")),
        Read::Fresh("English menu".to_string())
    );
}

#[test]
fn the_compatibility_generation_is_not_a_dimension_a_caller_supplies() {
    // Ruling of 2026-08-06, checked from the consuming side: the generation
    // arrives with the graph and goes to the materializer's constructor. There
    // is no `EntryKey` method that adds it and no policy that declares it, so a
    // caller cannot get it wrong by forgetting.
    let g = store_graph();
    assert!(
        !g.compatibility.is_empty(),
        "the compiler stamps every graph with the generation that produced it"
    );

    let key = EntryKey::new("store.menu_fragment.MenuFragment", &["47"]);
    let now = Materializer::new(Clock::new(), &g.compatibility);
    let later = Materializer::new(Clock::new(), "some-later-build");
    now.declare(
        "store.menu_fragment.MenuFragment",
        FragmentPolicy::default(),
    );
    later.declare(
        "store.menu_fragment.MenuFragment",
        FragmentPolicy::default(),
    );

    now.regenerate(&key, None, || Ok("markup".to_string()));
    assert_eq!(
        later.read(&key),
        Read::Missing,
        "a later build must not be served the previous generation's markup"
    );

    // And no declared dimension is named `code_version`, or the author would
    // still be being asked for it in a second place.
    for d in g.dimensions_of("store.menu_fragment.MenuFragment") {
        assert_ne!(
            d.key_name(),
            "code_version",
            "the generation is platform mechanism, not application policy"
        );
    }
}
