//! Type-directed boundary decoding.
//!
//! ADR-0011 §3–§4. The invariant:
//!
//! > No value crossing an erased backend boundary may be decoded without an
//! > expected static schema.
//!
//! The boundary never asks *"what Koka value is this `null`?"* — it cannot, because
//! E0 measured that `Nothing` and `Nil` are **both** `null` and are runtime
//! indistinguishable. It asks *"decode this payload **as** `Option<Int>`"*.
//!
//! Three modes, per ADR-0011:
//!
//! | mode | representation | guarantee |
//! |---|---|---|
//! | generated-to-generated | erased scalar + shared manifest | compiler-level |
//! | untyped / external | canonical form + structural validation | runtime-checked |
//! | debug / adversarial | tagged with type and constructor identity | detects cross-wiring |
//!
//! Note what is *not* claimed: at the optimized internal boundary a
//! `Money<USD>` really is a bare number, so nominal safety there is a property
//! of the compiler and the manifest, not of the payload. `docs/EVIDENCE_LEDGER.md`
//! records the wording this permits.

use serde_json::Value as Json;

use crate::types::{Program, Type};

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Mode {
    /// Both sides generated by `pw` from the same manifest. Payloads may be
    /// erased scalars; the expected type comes from the schema.
    Trusted,
    /// Anything else: another language, a network peer, a plugin, a human.
    /// Every field is validated structurally.
    Untyped,
    /// Payloads carry `$type` / `$case` so cross-wiring is *detected*, not merely
    /// prevented by construction. Costs allocation; used in tests and debug builds.
    Debug,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct DecodeError {
    pub path: String,
    pub expected: String,
    pub found: String,
}

impl std::fmt::Display for DecodeError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(
            f,
            "at {}: expected {}, found {}",
            self.path, self.expected, self.found
        )
    }
}

/// A decoded `pw` value. Note that `Opaque` retains the nominal type id: once a
/// value is decoded, the distinction Koka erased is back.
#[derive(Debug, Clone, PartialEq)]
pub enum Value {
    Bool(bool),
    Int(i64),
    Str(String),
    Opaque {
        ty: usize,
        inner: Box<Value>,
    },
    Ctor {
        adt: usize,
        ctor: usize,
        fields: Vec<Value>,
    },
    Tuple(Vec<Value>),
}

fn describe(v: &Json) -> String {
    match v {
        Json::Null => "null".into(),
        Json::Bool(b) => format!("bool({b})"),
        Json::Number(n) => format!("number({n})"),
        Json::String(s) => format!("string({:?})", truncate(s)),
        Json::Array(a) => format!("array(len {})", a.len()),
        Json::Object(o) => {
            let mut keys: Vec<&String> = o.keys().collect();
            keys.sort();
            format!(
                "object{{{}}}",
                keys.iter()
                    .map(|s| s.as_str())
                    .collect::<Vec<_>>()
                    .join(",")
            )
        }
    }
}

fn truncate(s: &str) -> String {
    if s.len() <= 24 {
        s.to_string()
    } else {
        format!("{}…", &s[..24])
    }
}

pub struct Decoder<'a> {
    pub program: &'a Program,
    pub mode: Mode,
}

impl<'a> Decoder<'a> {
    pub fn new(program: &'a Program, mode: Mode) -> Self {
        Self { program, mode }
    }

    /// The only entry point. There is deliberately no `decode_unknown(value)`:
    /// the expected type is always supplied by the caller.
    pub fn decode(
        &self,
        path: &str,
        expected: &Type,
        payload: &Json,
    ) -> Result<Value, DecodeError> {
        match expected {
            Type::Bool => payload
                .as_bool()
                .map(Value::Bool)
                .ok_or_else(|| self.err(path, "Bool", payload)),
            Type::Int => payload
                .as_i64()
                .map(Value::Int)
                .ok_or_else(|| self.err(path, "Int", payload)),
            Type::Str => payload
                .as_str()
                .map(|s| Value::Str(s.to_string()))
                .ok_or_else(|| self.err(path, "String", payload)),

            // A nominal wrapper. The payload is its representation — a bare
            // number for `Money<USD>`. The nominal identity comes from the
            // schema slot, which is exactly what makes this safe here and
            // unsafe at the raw Koka seam.
            Type::Opaque(id) => {
                let o = self.program.opaque(*id);
                if self.mode == Mode::Debug {
                    // In debug mode the payload must name its own type, so a
                    // Money<USD> handed to a Money<EUR> slot is caught.
                    if let Some(obj) = payload.as_object() {
                        let declared = obj.get("$type").and_then(|v| v.as_str());
                        if declared != Some(o.name.as_str()) {
                            return Err(DecodeError {
                                path: path.to_string(),
                                expected: format!("$type = {:?}", o.name),
                                found: format!("$type = {declared:?}"),
                            });
                        }
                        let inner = obj.get("value").unwrap_or(&Json::Null);
                        let v = self.decode(path, &o.representation, inner)?;
                        return Ok(Value::Opaque {
                            ty: *id,
                            inner: Box::new(v),
                        });
                    }
                    return Err(self.err(path, &format!("tagged {}", o.name), payload));
                }
                let inner = self.decode(path, &o.representation, payload)?;
                Ok(Value::Opaque {
                    ty: *id,
                    inner: Box::new(inner),
                })
            }

            Type::Tuple(elems) => {
                let arr = payload
                    .as_array()
                    .ok_or_else(|| self.err(path, &self.program.type_name(expected), payload))?;
                if arr.len() != elems.len() {
                    return Err(DecodeError {
                        path: path.to_string(),
                        expected: format!("tuple of {} elements", elems.len()),
                        found: format!("array(len {})", arr.len()),
                    });
                }
                let mut out = Vec::with_capacity(elems.len());
                for (i, (t, v)) in elems.iter().zip(arr).enumerate() {
                    out.push(self.decode(&format!("{path}.{i}"), t, v)?);
                }
                Ok(Value::Tuple(out))
            }

            Type::Adt(adt_id) => self.decode_adt(path, *adt_id, payload),
        }
    }

    fn decode_adt(&self, path: &str, adt_id: usize, payload: &Json) -> Result<Value, DecodeError> {
        let adt = self.program.adt(adt_id);

        // Canonical `pw` ABI form: {"$case": "Some", "values": [...]}.
        //
        // This is OUR representation, produced by generated codecs. It is not
        // Koka's `{_tag: N}` layout — depending on that would couple the ABI to
        // an undocumented internal whose tag integers renumber when a
        // constructor is inserted.
        let obj = payload
            .as_object()
            .ok_or_else(|| self.err(path, &adt.name, payload))?;

        let case = obj
            .get("$case")
            .and_then(|v| v.as_str())
            .ok_or_else(|| DecodeError {
                path: path.to_string(),
                expected: format!("{} with a $case tag", adt.name),
                found: describe(payload),
            })?;

        let idx = adt
            .ctors
            .iter()
            .position(|c| c.name == case)
            .ok_or_else(|| DecodeError {
                path: path.to_string(),
                expected: format!(
                    "one of {}",
                    adt.ctors
                        .iter()
                        .map(|c| c.name.as_str())
                        .collect::<Vec<_>>()
                        .join(" | ")
                ),
                found: format!("$case = {case:?}"),
            })?;

        let ctor = &adt.ctors[idx];
        let empty = Vec::new();
        let values = obj
            .get("values")
            .and_then(|v| v.as_array())
            .unwrap_or(&empty);

        if values.len() != ctor.fields.len() {
            return Err(DecodeError {
                path: path.to_string(),
                expected: format!("{} with {} field(s)", ctor.name, ctor.fields.len()),
                found: format!("{} value(s)", values.len()),
            });
        }

        let mut fields = Vec::with_capacity(ctor.fields.len());
        for (i, (t, v)) in ctor.fields.iter().zip(values).enumerate() {
            fields.push(self.decode(&format!("{path}.{}[{i}]", ctor.name), t, v)?);
        }
        Ok(Value::Ctor {
            adt: adt_id,
            ctor: idx,
            fields,
        })
    }

    fn err(&self, path: &str, expected: &str, found: &Json) -> DecodeError {
        DecodeError {
            path: path.to_string(),
            expected: expected.to_string(),
            found: describe(found),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::types::Ctor;
    use serde_json::json;

    #[test]
    fn option_and_list_cannot_be_confused_even_though_koka_makes_both_null() {
        // The E0 finding this exists to defeat: in Koka's JS output `Nothing`
        // and `Nil` are BOTH `null` and `is_nothing(Nil)` is true.
        //
        // Here the decoder is TOLD which type it is decoding, so the question
        // never arises.
        let mut p = Program::new();
        let opt = p.declare_option(Type::Int);
        let list = p.declare_list(Type::Int);
        let d = Decoder::new(&p, Mode::Untyped);

        let none = json!({ "$case": "None" });
        let nil = json!({ "$case": "Nil" });

        let a = d.decode("$", &Type::Adt(opt), &none).unwrap();
        let b = d.decode("$", &Type::Adt(list), &nil).unwrap();
        assert_ne!(a, b, "an empty Option and an empty List must not be equal");

        // And each rejects the other's tag rather than silently accepting it.
        assert!(d.decode("$", &Type::Adt(opt), &nil).is_err());
        assert!(d.decode("$", &Type::Adt(list), &none).is_err());
    }

    #[test]
    fn a_bare_null_is_never_accepted_for_either() {
        // Koka's raw representation would hand us `null` for both. The canonical
        // ABI has no such value, so it is a decode error, not a guess.
        let mut p = Program::new();
        let opt = p.declare_option(Type::Int);
        let list = p.declare_list(Type::Int);
        let d = Decoder::new(&p, Mode::Untyped);
        assert!(d.decode("$", &Type::Adt(opt), &json!(null)).is_err());
        assert!(d.decode("$", &Type::Adt(list), &json!(null)).is_err());
    }

    #[test]
    fn raw_primitive_cannot_enter_a_nominal_position_undetected_in_debug_mode() {
        // Trusted mode accepts a bare 350 for Money<USD> — that is the erased
        // fast path, and the guarantee there is compiler-level.
        // Debug mode requires the payload to name its own type, so a Money<EUR>
        // arriving in a Money<USD> slot is caught.
        let mut p = Program::new();
        let usd = p.declare_opaque("Money<USD>", Type::Int);
        let _eur = p.declare_opaque("Money<EUR>", Type::Int);

        let trusted = Decoder::new(&p, Mode::Trusted);
        let v = trusted
            .decode("$", &Type::Opaque(usd), &json!(350))
            .unwrap();
        assert_eq!(
            v,
            Value::Opaque {
                ty: usd,
                inner: Box::new(Value::Int(350))
            }
        );

        let debug = Decoder::new(&p, Mode::Debug);
        // A bare scalar is refused outright in debug mode.
        assert!(debug.decode("$", &Type::Opaque(usd), &json!(350)).is_err());
        // Correctly tagged: accepted.
        let ok = debug
            .decode(
                "$",
                &Type::Opaque(usd),
                &json!({"$type": "Money<USD>", "value": 350}),
            )
            .unwrap();
        assert_eq!(
            ok,
            Value::Opaque {
                ty: usd,
                inner: Box::new(Value::Int(350))
            }
        );
        // Cross-wired: rejected, and the error names both sides.
        let e = debug
            .decode(
                "$",
                &Type::Opaque(usd),
                &json!({"$type": "Money<EUR>", "value": 350}),
            )
            .unwrap_err();
        assert!(e.expected.contains("Money<USD>"), "{e}");
        assert!(e.found.contains("Money<EUR>"), "{e}");
    }

    #[test]
    fn decoding_is_type_directed_not_shape_directed() {
        // The same payload shape decodes to different values under different
        // expected types — which is only possible because the type is an input.
        let mut p = Program::new();
        let a = p.declare_opaque("StoreId", Type::Str);
        let b = p.declare_opaque("ConsumerId", Type::Str);
        let d = Decoder::new(&p, Mode::Trusted);
        let payload = json!("x_1");
        let va = d.decode("$", &Type::Opaque(a), &payload).unwrap();
        let vb = d.decode("$", &Type::Opaque(b), &payload).unwrap();
        assert_ne!(va, vb);
    }

    #[test]
    fn wrong_field_type_is_rejected_rather_than_coerced() {
        let mut p = Program::new();
        let store = p.declare_adt(
            "Store",
            vec![Ctor {
                name: "Store".into(),
                fields: vec![Type::Str, Type::Int],
            }],
        );
        let d = Decoder::new(&p, Mode::Untyped);
        let e = d
            .decode(
                "$",
                &Type::Adt(store),
                &json!({"$case":"Store","values":["s", "not an int"]}),
            )
            .unwrap_err();
        assert_eq!(e.expected, "Int");
        assert!(e.path.contains("Store"), "{e}");
    }

    #[test]
    fn unknown_constructor_lists_the_legal_ones() {
        let mut p = Program::new();
        let opt = p.declare_option(Type::Int);
        let d = Decoder::new(&p, Mode::Untyped);
        let e = d
            .decode("$", &Type::Adt(opt), &json!({"$case":"Just","values":[1]}))
            .unwrap_err();
        assert!(e.expected.contains("None"), "{e}");
        assert!(e.expected.contains("Some"), "{e}");
        assert!(e.found.contains("Just"), "{e}");
    }

    #[test]
    fn arity_mismatch_is_an_error() {
        let mut p = Program::new();
        let opt = p.declare_option(Type::Int);
        let d = Decoder::new(&p, Mode::Untyped);
        assert!(
            d.decode("$", &Type::Adt(opt), &json!({"$case":"Some","values":[]}))
                .is_err()
        );
        assert!(
            d.decode(
                "$",
                &Type::Adt(opt),
                &json!({"$case":"Some","values":[1,2]})
            )
            .is_err()
        );
    }

    #[test]
    fn nested_recursive_values_decode() {
        let mut p = Program::new();
        let list = p.declare_list(Type::Int);
        let d = Decoder::new(&p, Mode::Untyped);
        // Cons(1, Cons(2, Nil))
        let payload = json!({
            "$case": "Cons",
            "values": [1, { "$case": "Cons", "values": [2, { "$case": "Nil" }] }]
        });
        let v = d.decode("$", &Type::Adt(list), &payload).unwrap();
        match v {
            Value::Ctor { ctor, .. } => assert_eq!(ctor, 1),
            other => panic!("unexpected {other:?}"),
        }
    }
}
