//! HIR → Koka 3.2.3 source, for the pure subset (ADR-0015).
//!
//! This exists to answer charter §14 M2 gate item 4 — *a simple domain function
//! executes through generated Koka* — and to answer nothing else. ADR-0015
//! states what it is not evidence for; the short version is that only `!{}`
//! functions lower, so this path never sees an effect row, and E0 finding F-4
//! measured that Koka erases the nominal wrappers it does carry.
//!
//! Every generated function declares `total`. Under any other effect row Koka's
//! exhaustiveness check passes vacuously (E0 finding F-8), which would make
//! compiling the output worthless as a second opinion.

use std::collections::BTreeSet;

use crate::hir::{BinOp, Body, Decl, DeclKind, Expr, ExprId, Hir, Literal, Pattern, UnOp};

/// A declaration the subset does not cover, with the reason.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Skipped {
    pub name: String,
    pub reason: &'static str,
}

#[derive(Debug, Clone, Default)]
pub struct Lowered {
    pub source: String,
    pub skipped: Vec<Skipped>,
    /// Declarations that reached the output.
    pub emitted: Vec<String>,
}

/// Lower one module. `module_name` becomes the Koka module header.
pub fn lower_module(hir: &Hir, module_name: &str) -> Lowered {
    let mut out = Lowered::default();
    let mut body = String::new();

    // Only top-level declarations: a nested `fn` belongs to a UI declaration,
    // and UI declarations are outside the subset entirely.
    let top: BTreeSet<u32> = hir
        .modules
        .iter()
        .flat_map(|(_, m, _)| m.decls.iter().map(|d| d.0))
        .collect();

    for (id, decl) in hir.all_decls() {
        if !top.contains(&id.0) {
            continue;
        }
        match lower_decl(hir, decl) {
            Ok(Some(text)) => {
                out.emitted.push(decl.name.clone());
                body.push_str(&text);
                body.push('\n');
            }
            Ok(None) => {}
            Err(reason) => out.skipped.push(Skipped {
                name: decl.name.clone(),
                reason,
            }),
        }
    }

    out.source = format!(
        "// Generated by pw from `{module_name}`. Do not edit.\n\
         // ADR-0015: the pure subset only. Every function declares `total`,\n\
         // because Koka's exhaustiveness check is vacuous under any other row.\n\
         module {}\n\n{body}",
        koka_module_name(module_name)
    );
    out
}

fn lower_decl(hir: &Hir, decl: &Decl) -> Result<Option<String>, &'static str> {
    match decl.kind {
        DeclKind::Import | DeclKind::Let => Ok(None),

        // An effect DECLARATION is not a computation: it says how an effect
        // lowers to authority, which is E8's question and not Koka's.
        DeclKind::Effect => Err("an effect declaration is an ontology entry, not a computation"),

        // Nor is a prelude declaration. It says which namespace this package
        // exports ambiently — a statement about the language environment, with
        // no term to translate.
        DeclKind::Prelude => Err("a prelude declaration exports a namespace, not a computation"),

        // E6. Neither is a computation Koka could check: a materialization is
        // a scheduling decision the runtime makes and an event is a fact about
        // the world. Skipped with a reason rather than silently, so the
        // `emit-koka` skip list stays an accurate account of the gap.
        DeclKind::Materialize => Err("a materialization — the runtime schedules it"),
        DeclKind::Event => Err("an event declaration — no body to check"),

        DeclKind::Type => {
            // A record: `type CartLine = CartLine { item_id: .., .. }`.
            if let Some(fields) = &decl.fields {
                if fields.is_empty() {
                    return Err("a record with no fields");
                }
                let mut s = format!("pub value struct {}\n", type_name(&decl.name));
                for f in fields {
                    let Some(ty) = &f.ty else {
                        return Err("a record field with no declared type");
                    };
                    // The head AND its arguments. `f.ty` is the head alone, so
                    // `List<CartLine>` emitted `lines : list` — which Koka
                    // rejects, because `list` needs one. The THIRD instance of
                    // this shape found on 2026-08-08: `Interface::of` dropped
                    // arguments when asking whether a position carries a
                    // resource, and `wit.rs`'s record fields emitted `list`
                    // with nothing in it. Reading a type's head and calling it
                    // the type is apparently the easiest mistake in this
                    // codebase to make.
                    s.push_str(&format!(
                        "  {} : {}\n",
                        value_name(&f.name),
                        type_name(&crate::wit::written(ty, &f.ty_args))
                    ));
                }
                return Ok(Some(s));
            }
            let Some(variants) = &decl.variants else {
                return Err("a type alias with neither fields nor variants");
            };
            let mut s = format!("pub type {}\n", type_name(&decl.name));
            for v in variants {
                if v.fields.is_empty() {
                    s.push_str(&format!("  {}\n", v.name));
                } else {
                    let fields: Vec<String> = v
                        .fields
                        .iter()
                        .enumerate()
                        .map(|(i, f)| format!("field{i} : {}", type_name(f)))
                        .collect();
                    s.push_str(&format!("  {}( {} )\n", v.name, fields.join(", ")));
                }
            }
            Ok(Some(s))
        }

        DeclKind::Fn => {
            match decl.declared_effects.as_deref() {
                Some([]) => {}
                Some(_) => return Err("a non-empty effect row is outside the subset"),
                None => return Err("no declared effect row"),
            }
            let Some(body_id) = decl.body else {
                return Err("no body");
            };
            let body = hir.body(body_id);

            let params: Vec<String> = decl
                .params
                .iter()
                .map(|p| {
                    // Head and arguments, as above.
                    let ty = match &p.ty {
                        Some(head) => crate::wit::written(head, &p.ty_args),
                        None => "Int".to_string(),
                    };
                    format!("{} : {}", value_name(&p.name), type_name(&ty))
                })
                .collect();

            let Some(ret) = &decl.ret else {
                return Err("no declared return type");
            };
            let expr = lower_body(body)?;
            Ok(Some(format!(
                "pub fun {}( {} ) : total {}\n{}\n",
                value_name(&decl.name),
                params.join(", "),
                type_name(ret),
                indent(&expr, 1),
            )))
        }

        DeclKind::Opaque => Err("an opaque type is erased by Koka (E0 finding F-4)"),
        DeclKind::View | DeclKind::Component | DeclKind::Page => Err("a UI declaration"),
        DeclKind::Query | DeclKind::Command | DeclKind::Subscription => {
            Err("a data operation carries policies Koka cannot express")
        }
        DeclKind::Resource | DeclKind::Task => Err("a resource or task"),
        DeclKind::Other => Err("an unrecognised declaration form"),
    }
}

/// A body is a block; Koka takes its statements directly.
fn lower_body(body: &Body) -> Result<String, &'static str> {
    lower_expr(body, body.root)
}

fn lower_expr(b: &Body, id: ExprId) -> Result<String, &'static str> {
    Ok(match b.expr(id) {
        Expr::Literal(l) => match l {
            Literal::Int(s) | Literal::Float(s) => s.clone(),
            Literal::Str(s) => s.clone(),
            Literal::UnterminatedStr(_) => return Err("an unterminated string"),
        },

        Expr::Name(n) => {
            // A capitalised bare name is a nullary constructor; anything else
            // is a value, and Koka wants values lowercase.
            if starts_upper(n) {
                n.clone()
            } else {
                value_name(n)
            }
        }

        Expr::Field { base, name } => {
            format!("{}.{}", lower_expr(b, *base)?, value_name(name))
        }

        Expr::Call { callee, args } => {
            let head = match b.expr(*callee) {
                Expr::Name(n) if starts_upper(n) => ctor_name(n),
                Expr::Name(n) => value_name(n),
                // `Module.fn(..)` needs name resolution to lower correctly.
                Expr::Field { .. } => return Err("a qualified call"),
                _ => return Err("a computed callee"),
            };
            let mut parts = Vec::new();
            for a in args {
                if a.name.is_some() {
                    return Err("a named argument");
                }
                parts.push(lower_expr(b, a.value)?);
            }
            format!("{head}( {} )", parts.join(", "))
        }

        Expr::Binary { op, lhs, rhs } => {
            let o = match op {
                BinOp::Add => "+",
                BinOp::Sub => "-",
                BinOp::Mul => "*",
                BinOp::Div => "/",
                BinOp::Rem => "%",
                BinOp::And => "&&",
                BinOp::Or => "||",
                BinOp::Cmp(c) => match c.as_str() {
                    "==" | "!=" | "<" | ">" | "<=" | ">=" => c.as_str(),
                    _ => return Err("an unsupported comparison"),
                },
                BinOp::Pipe | BinOp::Transition | BinOp::Assign => {
                    return Err("a pipeline, transition or assignment");
                }
            };
            format!("({} {o} {})", lower_expr(b, *lhs)?, lower_expr(b, *rhs)?)
        }

        Expr::Unary { op, operand } => {
            let o = match op {
                UnOp::Neg => "-",
                UnOp::Not => "!",
            };
            format!("{o}{}", lower_expr(b, *operand)?)
        }

        Expr::If { cond, then, els } => {
            let mut s = format!(
                "if {} then\n{}",
                lower_expr(b, *cond)?,
                indent(&lower_expr(b, *then)?, 1)
            );
            if let Some(e) = els {
                s.push_str(&format!("\nelse\n{}", indent(&lower_expr(b, *e)?, 1)));
            }
            s
        }

        Expr::Match { scrutinee, arms } => {
            let mut s = format!("match {}\n", lower_expr(b, *scrutinee)?);
            for arm in arms {
                s.push_str(&format!(
                    "  {} -> {}\n",
                    lower_pattern(b, arm.pat)?,
                    lower_expr(b, arm.body)?
                ));
            }
            s.trim_end().to_string()
        }

        Expr::Block { stmts } => {
            let mut lines = Vec::new();
            for (i, st) in stmts.iter().enumerate() {
                let last = i + 1 == stmts.len();
                match b.expr(*st) {
                    Expr::Let { pat, init, .. } => {
                        let name = match pat.map(|p| b.pat(p)) {
                            Some(Pattern::Bind { name, .. }) => value_name(name),
                            _ => return Err("a destructuring binding"),
                        };
                        let Some(init) = init else {
                            return Err("a binding with no initialiser");
                        };
                        lines.push(format!("val {name} = {}", lower_expr(b, *init)?));
                    }
                    _ if last => lines.push(lower_expr(b, *st)?),
                    _ => return Err("a statement that is not a binding or the result"),
                }
            }
            if lines.is_empty() {
                return Err("an empty body");
            }
            lines.join("\n")
        }

        Expr::Let { .. } => return Err("a binding outside a block"),
        Expr::Lambda { .. } => return Err("a lambda"),
        Expr::Record { .. } => return Err("a record literal"),
        Expr::List { .. } => return Err("a collection literal"),
        Expr::Keyword { .. } => return Err("a body-level statement"),
        Expr::Template { .. } => return Err("markup"),
        // Deliberately refused rather than erased. ADR-0015 keeps the Koka
        // backend to the pure subset, and a cast is exactly the boundary the
        // corpus says must go through a decoder — emitting one silently would
        // make the oracle agree with a program `pw` rejects.
        Expr::Cast { .. } => return Err("a cast"),
        Expr::Interpolated { .. } => return Err("an interpolated string"),
        Expr::Error => return Err("an expression that did not parse"),
    })
}

fn lower_pattern(b: &Body, id: crate::hir::PatternId) -> Result<String, &'static str> {
    Ok(match b.pat(id) {
        Pattern::Wild => "_".to_string(),
        Pattern::Bind { name, .. } => {
            // A binding that names a constructor IS the constructor — the same
            // ambiguity the exhaustiveness bridge resolves, and getting it wrong
            // here would silently turn an arm into a catch-all.
            if starts_upper(name) {
                name.clone()
            } else {
                value_name(name)
            }
        }
        Pattern::Ctor { path, args } => {
            let head = path.rsplit('.').next().unwrap_or(path);
            if args.is_empty() {
                head.to_string()
            } else {
                let parts: Result<Vec<_>, _> = args.iter().map(|a| lower_pattern(b, *a)).collect();
                format!("{head}( {} )", parts?.join(", "))
            }
        }
        Pattern::Literal(Literal::Int(s) | Literal::Float(s) | Literal::Str(s)) => s.clone(),
        Pattern::Literal(_) => return Err("an unsupported literal pattern"),
        Pattern::Or(_) => return Err("an or-pattern"),
        Pattern::Error => return Err("a pattern that did not parse"),
    })
}

// --- names ---------------------------------------------------------------

fn starts_upper(s: &str) -> bool {
    s.chars().next().is_some_and(char::is_uppercase)
}

/// `store.pricing` → `store_pricing`.
fn koka_module_name(m: &str) -> String {
    m.replace('.', "_")
}

/// Koka type names start lowercase: `CartLine` → `cart_line`.
fn type_name(t: &str) -> String {
    match t {
        "Int" => return "int".into(),
        "String" | "Str" => return "string".into(),
        "Bool" => return "bool".into(),
        "()" => return "()".into(),
        _ => {}
    }
    // `List<CartLine>` -> `list<cart_line>`. Koka spells a type application the
    // same way, so the arguments are mapped and the brackets kept — dropping
    // them produced `list`, which Koka rejects for the arity it needs.
    if let Some((head, rest)) = t.split_once('<') {
        let args: Vec<String> = rest
            .trim_end_matches('>')
            .split(',')
            .map(str::trim)
            .filter(|a| !a.is_empty())
            .map(type_name)
            .collect();
        if !args.is_empty() {
            return format!("{}<{}>", type_name(head.trim()), args.join(", "));
        }
        return type_name(head.trim());
    }
    // Snake case, with a separator only where a word actually starts: after a
    // lowercase letter or a digit. Separating on EVERY uppercase character
    // turned `USD` into `u_s_d`, which reads as three type names — visible only
    // once a generic argument was carried through and `Money<USD>` reached
    // here at all.
    let mut out = String::new();
    let mut prev_lower = false;
    for c in t.chars() {
        if c.is_uppercase() {
            if prev_lower {
                out.push('_');
            }
            out.extend(c.to_lowercase());
            prev_lower = false;
        } else {
            out.push(c);
            prev_lower = c.is_lowercase() || c.is_ascii_digit();
        }
    }
    out
}

/// The constructor Koka derives for a record: the type name with its first
/// letter capitalised. `CartLine` → struct `cart_line` → constructor `Cart_line`.
fn ctor_name(t: &str) -> String {
    let n = type_name(t);
    let mut cs = n.chars();
    match cs.next() {
        Some(c) => c.to_uppercase().collect::<String>() + cs.as_str(),
        None => n,
    }
}

/// Values and functions are already lowercase in `pw`; this guards the rest.
fn value_name(v: &str) -> String {
    let mut out = String::new();
    for (i, c) in v.chars().enumerate() {
        if c.is_uppercase() {
            if i > 0 {
                out.push('_');
            }
            out.extend(c.to_lowercase());
        } else {
            out.push(c);
        }
    }
    out
}

fn indent(s: &str, levels: usize) -> String {
    let pad = "  ".repeat(levels);
    s.lines()
        .map(|l| {
            if l.is_empty() {
                String::new()
            } else {
                format!("{pad}{l}")
            }
        })
        .collect::<Vec<_>>()
        .join("\n")
}
