//! HIR → Marko 6 templates (ADR-0017).
//!
//! The E3 adapter. Marko is **tape** (ADR-0002): it renders while `pw`'s own
//! renderer does not exist, and it is removable because this module reads HIR
//! and writes files into a build directory — nothing else depends on it.
//!
//! Two rules keep the adapter from quietly becoming the language:
//!
//! 1. **HIR is the only input.** A construct that is not modelled cannot be
//!    emitted, and the fix is to model it — not to special-case it here.
//! 2. **Unsupported constructs are reported, never approximated.** An
//!    approximation renders, which is worse than not rendering: the page looks
//!    right and is wrong.
//!
//! Every mapping was verified against Marko 6.3.32 templates that compile and
//! serve (`spikes/marko-stream-resume`), not read from documentation.

use crate::hir::{
    AttrValue, Body, Decl, DeclKind, Expr, ExprId, Hir, Literal, Node, NodeId, Pattern,
};

/// A declaration the adapter could not render, and why.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Skipped {
    pub name: String,
    pub reason: String,
}

#[derive(Debug, Clone, Default)]
pub struct Rendered {
    /// `(file name, contents)`, ready to write under a build directory.
    pub files: Vec<(String, String)>,
    pub skipped: Vec<Skipped>,
}

/// Lower every renderable declaration in a module.
pub fn render_module(hir: &Hir, source_name: &str) -> Rendered {
    let mut out = Rendered::default();
    for (_, decl) in hir.all_decls() {
        if !matches!(
            decl.kind,
            DeclKind::View | DeclKind::Component | DeclKind::Page
        ) {
            continue;
        }
        match render_decl(hir, decl, source_name) {
            Ok(text) => out.files.push((format!("{}.marko", decl.name), text)),
            Err(reason) => out.skipped.push(Skipped {
                name: decl.name.clone(),
                reason,
            }),
        }
    }
    out
}

fn render_decl(hir: &Hir, decl: &Decl, source_name: &str) -> Result<String, String> {
    let body_id = decl.body.ok_or_else(|| "no body".to_string())?;
    let body = hir.body(body_id);

    // The markup is whatever template regions the body contains. A view with
    // none renders nothing, which is a bug in the source, not in the adapter.
    let mut roots: Vec<NodeId> = Vec::new();
    for id in body.walk() {
        if let Expr::Template { roots: r, .. } = body.expr(id) {
            roots.extend(r.iter().copied());
        }
    }
    if roots.is_empty() {
        return Err("no markup to render".to_string());
    }

    let mut out = String::new();
    out.push_str(&banner(source_name, &decl.name));

    // A view's own bindings become Marko state. `let mut` is reactive state
    // (`<let/…>`); an immutable binding is a computed constant (`<const/…>`).
    // Without this the counter has nothing to increment.
    let params: Vec<String> = decl.params.iter().map(|p| p.name.clone()).collect();
    let ctx = Ctx { params: &params };
    let mut bindings = String::new();
    if let Expr::Block { stmts } = body.expr(body.root) {
        for st in stmts {
            let Expr::Let { pat, init, .. } = body.expr(*st) else {
                continue;
            };
            let (Some(pat), Some(init)) = (pat, init) else {
                continue;
            };
            let Pattern::Bind { name, mutable } = body.pat(*pat) else {
                continue;
            };
            let kw = if *mutable { "let" } else { "const" };
            bindings.push_str(&format!(
                "<{kw}/{name}={}>\n",
                expr_text(body, *init, &ctx)?
            ));
        }
    }
    if !bindings.is_empty() {
        out.push_str(&bindings);
        out.push('\n');
    }

    for r in &roots {
        emit_node(body, *r, 0, &ctx, &mut out)?;
    }
    Ok(out)
}

/// What a name means in this template. A view's parameters arrive as `input`
/// in Marko; its own bindings are plain locals.
struct Ctx<'a> {
    params: &'a [String],
}

impl Ctx<'_> {
    fn name(&self, n: &str) -> String {
        if self.params.iter().any(|p| p == n) {
            format!("input.{n}")
        } else {
            n.to_string()
        }
    }
}

fn banner(source_name: &str, decl: &str) -> String {
    format!(
        "// GENERATED by pw from `{source_name}` ({decl}). Do not edit.\n\
         // ADR-0017: this file is build output. Editing it makes the `.pw`\n\
         // source no longer the truth, and the adapter no longer removable.\n\n"
    )
}

fn emit_node(
    body: &Body,
    id: NodeId,
    depth: usize,
    ctx: &Ctx<'_>,
    out: &mut String,
) -> Result<(), String> {
    let pad = "  ".repeat(depth);
    match body.node(id) {
        Node::Text(t) => {
            // Marko treats `${` as an interpolation, so literal text that
            // contains it would change meaning. Refuse rather than mangle.
            if t.contains("${") {
                return Err("text containing `${` cannot be rendered verbatim".to_string());
            }
            let trimmed = t.trim();
            if !trimmed.is_empty() {
                out.push_str(&format!("{pad}{trimmed}\n"));
            }
            Ok(())
        }

        Node::Interpolation(e) => {
            out.push_str(&format!("{pad}${{{}}}\n", expr_text(body, *e, ctx)?));
            Ok(())
        }

        Node::Block { directive, .. } => Err(format!(
            "the `{}` directive is not modelled yet; E4 owns its structure",
            directive.trim_matches(|c| c == '{' || c == '}')
        )),

        Node::Element {
            tag,
            attrs,
            children,
            self_closing,
        } => {
            let mut head = format!("{pad}<{tag}");
            for a in attrs {
                head.push(' ');
                head.push_str(&attr_text(body, a, ctx)?);
            }
            if *self_closing {
                out.push_str(&format!("{head} />\n"));
                return Ok(());
            }

            // Whitespace with a newline in it is formatting; whitespace without
            // one is content. That is exactly the distinction the author made by
            // writing `<span>a</span> <span>b</span>` on one line, and it decides
            // the layout here.
            //
            // The first version assumed block layout was safe because "HTML
            // collapses the newline back to a space". It does not: **Marko
            // strips whitespace between elements in the template**, so the page
            // rendered "Espresso$3.50". A template-level test could not see
            // that — the template was fine. The browser test caught it.
            let inline = children.iter().any(|c| match body.node(*c) {
                Node::Text(t) => !t.contains('\n'),
                Node::Interpolation(_) => true,
                _ => false,
            });
            if inline {
                let mut buf = String::new();
                for c in children {
                    emit_inline(body, *c, ctx, &mut buf)?;
                }
                out.push_str(&format!("{head}>{}</{tag}>\n", buf.trim_end()));
                return Ok(());
            }

            out.push_str(&format!("{head}>\n"));
            for c in children {
                emit_node(body, *c, depth + 1, ctx, out)?;
            }
            out.push_str(&format!("{pad}</{tag}>\n"));
            Ok(())
        }
    }
}

/// One node, with no added whitespace. Used inside mixed content, where every
/// space is part of what the page renders.
fn emit_inline(body: &Body, id: NodeId, ctx: &Ctx<'_>, out: &mut String) -> Result<(), String> {
    match body.node(id) {
        Node::Text(t) => {
            if t.contains("${") {
                return Err("text containing `${` cannot be rendered verbatim".to_string());
            }
            out.push_str(t);
            Ok(())
        }
        Node::Interpolation(e) => {
            out.push_str(&format!("${{{}}}", expr_text(body, *e, ctx)?));
            Ok(())
        }
        Node::Block { directive, .. } => Err(format!(
            "the `{}` directive is not modelled yet; E4 owns its structure",
            directive.trim_matches(|c| c == '{' || c == '}')
        )),
        Node::Element {
            tag,
            attrs,
            children,
            self_closing,
        } => {
            out.push('<');
            out.push_str(tag);
            for a in attrs {
                out.push(' ');
                out.push_str(&attr_text(body, a, ctx)?);
            }
            if *self_closing {
                out.push_str(" />");
                return Ok(());
            }
            out.push('>');
            for c in children {
                emit_inline(body, *c, ctx, out)?;
            }
            out.push_str(&format!("</{tag}>"));
            Ok(())
        }
    }
}

fn attr_text(body: &Body, a: &crate::hir::Attr, ctx: &Ctx<'_>) -> Result<String, String> {
    match (&a.value, a.namespace()) {
        // `on:press={h}` -> `onClick() { h }`. The event name is translated
        // rather than passed through: `press` is a *semantic* event in `pw` and
        // `onClick` is a DOM one, and conflating them is how a language ends up
        // shaped like its renderer.
        (AttrValue::Expr(e), Some(("on", event))) => {
            let dom = dom_event(event)?;
            Ok(format!("{dom}() {{ {} }}", expr_text(body, *e, ctx)?))
        }
        (_, Some(("on", _))) => Err("an `on:` attribute needs a handler expression".to_string()),

        (AttrValue::Expr(e), Some((ns, _))) => Err(format!(
            "the `{ns}:` attribute namespace is not modelled yet ({})",
            expr_text(body, *e, ctx).unwrap_or_default()
        )),
        (_, Some((ns, _))) => Err(format!(
            "the `{ns}:` attribute namespace is not modelled yet"
        )),

        (AttrValue::Static(v), None) => Ok(format!("{}={}", a.name, v)),
        (AttrValue::Expr(e), None) => Ok(format!("{}={}", a.name, expr_text(body, *e, ctx)?)),
        (AttrValue::None, None) => Ok(a.name.clone()),
    }
}

/// `pw`'s semantic events, mapped to DOM events.
///
/// Deliberately a closed list. Passing an unknown name straight through would
/// let a `.pw` file address the DOM directly, which is exactly the coupling
/// charter §11 says to avoid.
fn dom_event(event: &str) -> Result<&'static str, String> {
    Ok(match event {
        "press" => "onClick",
        "change" => "onChange",
        "input" => "onInput",
        "submit" => "onSubmit",
        "focus" => "onFocus",
        "blur" => "onBlur",
        other => return Err(format!("the `{other}` event is not modelled yet")),
    })
}

/// An expression, as Marko source.
///
/// Marko's expression syntax is JavaScript. The subset here is what a template
/// needs and no more; anything else is refused so it cannot silently render as
/// something that happens to be valid JavaScript with different meaning.
fn expr_text(body: &Body, id: ExprId, ctx: &Ctx<'_>) -> Result<String, String> {
    Ok(match body.expr(id) {
        Expr::Name(n) => ctx.name(n),
        Expr::Literal(Literal::Int(s) | Literal::Float(s) | Literal::Str(s)) => s.clone(),
        Expr::Literal(Literal::UnterminatedStr(_)) => {
            return Err("an unterminated string".to_string());
        }
        Expr::Field { base, name } => format!("{}.{}", expr_text(body, *base, ctx)?, name),
        Expr::Call { callee, args } => {
            let mut parts = Vec::new();
            for a in args {
                parts.push(expr_text(body, a.value, ctx)?);
            }
            format!("{}({})", expr_text(body, *callee, ctx)?, parts.join(", "))
        }
        Expr::Binary { op, lhs, rhs } => {
            let o = js_binop(op)?;
            format!(
                "{} {o} {}",
                expr_text(body, *lhs, ctx)?,
                expr_text(body, *rhs, ctx)?
            )
        }
        other => return Err(format!("{} is not renderable", describe(other))),
    })
}

fn js_binop(op: &crate::hir::BinOp) -> Result<&'static str, String> {
    use crate::hir::BinOp::*;
    Ok(match op {
        Add => "+",
        Sub => "-",
        Mul => "*",
        Div => "/",
        Rem => "%",
        And => "&&",
        Or => "||",
        Cmp(c) => match c.as_str() {
            "==" => "===",
            "!=" => "!==",
            "<" => "<",
            ">" => ">",
            "<=" => "<=",
            ">=" => ">=",
            _ => return Err("an unsupported comparison".to_string()),
        },
        // Assignment is what an event handler does: `on:press={count = count + 1}`.
        Assign => "=",
        Pipe | Transition => return Err("a pipeline or transition".to_string()),
    })
}

fn describe(e: &Expr) -> &'static str {
    match e {
        Expr::Lambda { .. } => "a lambda",
        Expr::Match { .. } => "a match",
        Expr::If { .. } => "an if expression",
        Expr::Block { .. } => "a block",
        Expr::Record { .. } => "a record literal",
        Expr::List { .. } => "a collection literal",
        Expr::Let { .. } => "a binding",
        Expr::Keyword { .. } => "a body-level statement",
        Expr::Template { .. } => "nested markup",
        Expr::Unary { .. } => "a unary operator",
        Expr::Error => "an expression that did not parse",
        _ => "this expression",
    }
}
